### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [cies/htoml#21]
```
htoml                          > Building library for htoml-1.0.0.3..
htoml                          > [1 of 3] Compiling Text.Toml.Types
htoml                          > 
htoml                          > /tmp/stack-89f3a8327c6d452d/htoml-1.0.0.3/src/Text/Toml/Types.hs:193:23: error:
htoml                          >     • Couldn't match type: HashMap Text Value
htoml                          >                      with: Data.Aeson.KeyMap.KeyMap Value
htoml                          >       Expected: HashMap Text v -> Object
htoml                          >         Actual: HashMap Text v -> HashMap Text Value
htoml                          >     • In the second argument of ‘(.)’, namely ‘M.map toBsJSON’
htoml                          >       In the expression: Object . M.map toBsJSON
htoml                          >       In an equation for ‘toBsJSON’: toBsJSON = Object . M.map toBsJSON
htoml                          >     |
htoml                          > 193 |   toBsJSON = Object . M.map toBsJSON
htoml                          >     |                       ^^^^^^^^^^^^^^
```
